const db = require("../config/db");

const getAllMza = async (id,codccpp, zona_id) => {
  return await db.T_manzana.findAll({ where: { ID: id,
    CODCCPP: codccpp,
    ZONA_ID: zona_id, }});
};

const findMzaById = async (id,codccpp, zona_id, manzana_id) => {
  //console.log('findMzaById id : ' + id + ' - codccpp : ' + codccpp + ' - zona_id : ' + zona_id  + ' - manzana_id : ' + manzana_id)
  return await db.T_manzana.findOne({
    where: {
      ID: id,
      CODCCPP: codccpp,
      ZONA_ID: zona_id,
      MANZANA_ID: manzana_id,
    }
  });
};

const createMza = async ({ ID, CODCCPP, ZONA_ID, MANZANA_ID, ESTADO, FOTO, CONGLOMERADO, FRENTES_SISFOH, TOTAL_VIVIENDAS, TOTAL_VIVIENDAS_MARCO, TIPO, TOTAL_VIVIENDAS_GESTOR, PRE_ESTADO, OBSERVACION, REAJUSTADA, AGREGADA, ACTCART, CANT, USU_ID, COD_OPER, TIPO_SEG, PERIODO, UBIGEO_C, TOTALESTA, TOTCOM, TOTINCOM, TOTAUSE, TOTRECHA, TOTNOIVI, TOTOTRO, TOTESTCONC, DNI_INI, DNI_FIN, FECHA_EMP, USUCRE, FECCRE, USUREG, FECREG, FECENV }) => {
  const newMza = await db.T_manzana.create({ ID, CODCCPP, ZONA_ID, MANZANA_ID, ESTADO, FOTO, CONGLOMERADO, FRENTES_SISFOH, TOTAL_VIVIENDAS, TOTAL_VIVIENDAS_MARCO, TIPO, TOTAL_VIVIENDAS_GESTOR, PRE_ESTADO, OBSERVACION, REAJUSTADA, AGREGADA, ACTCART, CANT, USU_ID, COD_OPER, TIPO_SEG, PERIODO, UBIGEO_C, TOTALESTA, TOTCOM, TOTINCOM, TOTAUSE, TOTRECHA, TOTNOIVI, TOTOTRO, TOTESTCONC, DNI_INI, DNI_FIN, FECHA_EMP, USUCRE, FECCRE, USUREG, FECREG, FECENV });
  return newMza;
};

const updateMza = async ({ ID, CODCCPP, ZONA_ID, MANZANA_ID, ESTADO, FOTO, CONGLOMERADO, FRENTES_SISFOH, TOTAL_VIVIENDAS, TOTAL_VIVIENDAS_MARCO, TIPO, TOTAL_VIVIENDAS_GESTOR, PRE_ESTADO, OBSERVACION, REAJUSTADA, AGREGADA, ACTCART, CANT, USU_ID, COD_OPER, TIPO_SEG, PERIODO, UBIGEO_C, TOTALESTA, TOTCOM, TOTINCOM, TOTAUSE, TOTRECHA, TOTNOIVI, TOTOTRO, TOTESTCONC, DNI_INI, DNI_FIN, FECHA_EMP, USUCRE, FECCRE, USUREG, FECREG, FECENV }) => {
  await db.T_manzana.update(
    { ID, CODCCPP, ZONA_ID, MANZANA_ID, ESTADO, FOTO, CONGLOMERADO, FRENTES_SISFOH, TOTAL_VIVIENDAS, TOTAL_VIVIENDAS_MARCO, TIPO, TOTAL_VIVIENDAS_GESTOR, PRE_ESTADO, OBSERVACION, REAJUSTADA, AGREGADA, ACTCART, CANT, USU_ID, COD_OPER, TIPO_SEG, PERIODO, UBIGEO_C, TOTALESTA, TOTCOM, TOTINCOM, TOTAUSE, TOTRECHA, TOTNOIVI, TOTOTRO, TOTESTCONC, DNI_INI, DNI_FIN, FECHA_EMP, USUCRE, FECCRE, USUREG, FECREG, FECENV },
    {
      where: {
        ID: ID,
        CODCCPP: CODCCPP,
        ZONA_ID: ZONA_ID,
        MANZANA_ID: MANZANA_ID,
      },
    }
  );
  return { ID, CODCCPP, ZONA_ID, MANZANA_ID, ESTADO, FOTO, CONGLOMERADO, FRENTES_SISFOH, TOTAL_VIVIENDAS, TOTAL_VIVIENDAS_MARCO, TIPO, TOTAL_VIVIENDAS_GESTOR, PRE_ESTADO, OBSERVACION, REAJUSTADA, AGREGADA, ACTCART, CANT, USU_ID, COD_OPER, TIPO_SEG, PERIODO, UBIGEO_C, TOTALESTA, TOTCOM, TOTINCOM, TOTAUSE, TOTRECHA, TOTNOIVI, TOTOTRO, TOTESTCONC, DNI_INI, DNI_FIN, FECHA_EMP, USUCRE, FECCRE, USUREG, FECREG, FECENV };
};

const deleteMza = async (Id, Codccpp, Zona_id, Manzana_id) => {
  await db.T_manzana.destroy({
    where: { ID: Id , CODCCPP: Codccpp, ZONA_ID: Zona_id, MANZANA_ID:Manzana_id },
  });
};


module.exports = {
    getAllMza,
    findMzaById,
    createMza,
    updateMza,
    deleteMza,  
};